name = "ILMPostProcessing"
uuid = "3d549a52-7b57-4935-b05e-d5b0ee0c7825"
authors = ["Jeff Eldredge <jdeldre@g.ucla.edu>"]
version = "0.1.0"

[deps]
ImmersedLayers = "cdc13194-334e-4e1c-bc8d-fc3a28509c85"

[compat]
ImmersedLayers = "0.5"
